# Generated by Django 4.1.12 on 2023-10-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_navigationsettings_mastodon_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='linked_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='Linkedin URL'),
        ),
    ]
